name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        bun-version: [latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ matrix.bun-version }}
        
    - name: Install dependencies
      run: bun install --frozen-lockfile
      
    # - name: Run linter
    #   run: bun run lint
    # Currently, CheckoutForm.test.tsx and BookingPage.tsx will fail
      
    - name: Run type checking
      run: bun run build
      
    - name: Run tests
      run: bun run test
